drivers: thermal: fix undeclared 'NULL' argument
fix undeclared 'NULL' argument after commit c1b91144530f041e55c764bdb425b02af2abb6b6 & 50b36ad84f586ff43362a386a6e0963f4fc737fa

with error:

../drivers/thermal/thermal_core.c:846:40: error: too few arguments to function call, expected 3, have 2
                thermal_zone_device_set_polling(tz, 0);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      ^
../drivers/thermal/thermal_core.c:820:1: note: 'thermal_zone_device_set_polling' declared here
static void thermal_zone_device_set_polling(struct workqueue_struct *queue,
^
../drivers/thermal/thermal_core.c:2380:40: error: too few arguments to function call, expected 3, have 2
                thermal_zone_device_set_polling(tz, 0);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      ^
../drivers/thermal/thermal_core.c:820:1: note: 'thermal_zone_device_set_polling' declared here
static void thermal_zone_device_set_polling(struct workqueue_struct *queue,

Signed-off-by: Dicky Herlambang <herlambangdicky5@gmail.com>